# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yzk5V4Ga7j4Kc4All5HAPVUjmA0aqRjb
"""

import pandas as pd
import requests
from bs4 import BeautifulSoup

url="http://pastic.gov.pk/database-universities.aspx"
page=requests.get(url)
page

Soup=BeautifulSoup(page.content,"html5")

name=Soup.find(class_="col-md-4 col-sm-5 logo")
print(name.text)

data=Soup.find(class_="top-content")
print(data.text)

data=[[name,data]]
df=pd.DataFrame(data,columns=["name","data"])
print(df)
df.to_csv("Universities Data.csv")
print("ok")